name: test_f2py
channels:
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2018.03.07=0
  - certifi=2018.4.16=py36_0
  - intel-openmp=2018.0.0=8
  - libgfortran-ng=7.2.0=hdf63c60_3
  - mkl=2018.0.2=1
  - mkl_fft=1.0.1=py36h3010b51_0
  - mkl_random=1.0.1=py36h629b387_0
  - notebook=5.5.0=py36_0
  - numpy=1.14.3=py36hcd700cb_1
  - numpy-base=1.14.3=py36h9be14a7_1
  - openssl=1.0.2o=h20670df_0
  - scipy=1.1.0=py36hfc37229_0
  - ecmwfapi=1.4.1=py36_1
  - backcall=0.1.0=py_0
  - bleach=2.1.3=py_0
  - cftime=1.0.0=py36_0
  - curl=7.60.0=0
  - cycler=0.10.0=py36_0
  - dbus=1.11.0=0
  - decorator=4.3.0=py_0
  - entrypoints=0.2.3=py36_1
  - expat=2.2.5=0
  - fontconfig=2.13.0=0
  - freetype=2.8.1=0
  - gmp=6.1.2=0
  - hdf4=4.2.13=0
  - hdf5=1.10.1=2
  - html5lib=1.0.1=py_0
  - icu=58.2=0
  - ipykernel=4.8.2=py36_0
  - ipython=6.4.0=py36_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.2.1=py36_1
  - jedi=0.12.0=py36_0
  - jinja2=2.10=py36_0
  - jpeg=9b=2
  - jsonschema=2.6.0=py36_1
  - jupyter=1.0.0=py_1
  - jupyter_client=5.2.3=py36_0
  - jupyter_console=5.2.0=py36_0
  - jupyter_core=4.4.0=py_0
  - kiwisolver=1.0.1=py36_1
  - krb5=1.14.6=0
  - libiconv=1.15=0
  - libnetcdf=4.6.1=2
  - libpng=1.6.34=0
  - libsodium=1.0.16=0
  - libssh2=1.8.0=2
  - libuuid=1.0.3=1
  - libxcb=1.13=0
  - libxml2=2.9.8=0
  - markupsafe=1.0=py36_0
  - matplotlib=2.2.2=py36_1
  - mistune=0.8.3=py36_1
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py36_0
  - netcdf4=1.4.0=py36_0
  - pandoc=2.2.1=0
  - pandocfilters=1.4.2=py36_0
  - parso=0.2.1=py_0
  - pcre=8.41=1
  - pexpect=4.5.0=py36_0
  - pickleshare=0.7.4=py36_0
  - prompt_toolkit=1.0.15=py36_0
  - ptyprocess=0.5.2=py36_0
  - pygments=2.2.0=py36_0
  - pyparsing=2.2.0=py36_0
  - pyqt=5.6.0=py36_5
  - python-dateutil=2.7.3=py_0
  - pytz=2018.4=py_0
  - pyzmq=17.0.0=py36_4
  - qtconsole=4.3.1=py36_0
  - send2trash=1.5.0=py_0
  - simplegeneric=0.8.1=py36_0
  - sip=4.18=py36_1
  - six=1.11.0=py36_1
  - terminado=0.8.1=py36_0
  - testpath=0.3.1=py36_0
  - tornado=5.0.2=py36_0
  - traitlets=4.3.2=py36_0
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5=py36_0
  - widgetsnbextension=3.2.1=py36_0
  - xorg-libxau=1.0.8=3
  - xorg-libxdmcp=1.1.2=3
  - zeromq=4.2.5=1
  - glib=2.53.6=h5d9569c_2
  - gst-plugins-base=1.12.4=h33fb286_0
  - gstreamer=1.12.4=hb53b477_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=7.2.0=hdf63c60_3
  - libgfortran=3.0.0=1
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - ncurses=6.1=hf484d3e_0
  - pip=10.0.1=py36_0
  - python=3.6.5=hc3d631a_2
  - qt=5.6.2=h974d657_12
  - readline=7.0=ha6073c6_4
  - setuptools=39.1.0=py36_0
  - sqlite=3.23.1=he433501_0
  - tk=8.6.7=hc745277_3
  - wheel=0.31.1=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=ha838bed_2
  - pip:
    - ecmwf-api-client==1.4.2
    - hn2016-falwa==0.3.2
prefix: /home/csyhuang/anaconda3/envs/test_f2py

